### ISSUE TITLE
The trained model for generating layouts

### ISSUE THREAD

**Issue by JupiterXiaoxiaoYu** [robvanvolt/DALLE-models#1]
Hi! I have seen your results of the trained model on generating the layouts from [lucidrains,]( https://github.com/lucidrains/DALLE-pytorch) that's amazing! And I want to continue to train it or do some fine-tuning to see if it could generate better results, could you tell me how you trained that model, for example, where you found the 150k layouts dataset and how you make the different areas into a row in different colours and let the model learn the different areas? Could you please provide the checkpoint of the model or tell me how to access the trained model?

**Comment by robvanvolt** [comment]
https://github.com/robvanvolt/DALLE-models/tree/main/models/taming_transformer
