### ISSUE TITLE
python3: can't open file '/content/dalle-pytorch-pretrained/DALLE-pytorch/generate.py'

### ISSUE THREAD

**Issue by tarsyang** [robvanvolt/DALLE-models#16]
change
!wget "https://github.com/lucidrains/DALLE-pytorch/archive/refs/tags/0.14.3.zip" -O /content/
to
!wget "https://github.com/lucidrains/DALLE-pytorch/archive/refs/tags/0.14.3.zip" -O /content/0.14.3.zip

**Comment by fdchiu** [comment]
I am getting the same error.
